name: Deploy Bot

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Start Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          STRING_SESSION: ${{ secrets.STRING_SESSION }}
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          LOG_GROUP_ID: ${{ secrets.LOG_GROUP_ID }}
        run: python3 -m YukkiMusic
